[package]
name = "irc"
version = "1.0.1"
authors = ["Axel Magnuson <axelmagn@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
docopt = "0.6"
rustc-serialize = "0.3"
uuid = { version = "0.3", features = ["rustc-serialize", "v4"] }
